### ISSUE TITLE
Why make another binding when this is already on nuget

### ISSUE THREAD

**Issue by martijn00** [NAXAM/cameraview-android-binding#1]
https://github.com/martijn00/CameraViewXamarin

**Comment by fleuverouge** [comment]
Hi @martijn00, thanks for the link.
I also wonder why Apple makes phones while Samsung is already producing many 🤔

**Comment by tuyen-vuduc** [comment]
@martijn00 Yeah, that's the nature of open source, I guess. There are a lot of duplications. 

When we were creating the binding, we didn't notice that you made it before.

BTW, we made the binding from the latest code from Google repo.

Cheers.
